//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedbackCollection.Models.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeDislike
    {
        public int Id { get; set; }
        public int CmntLike { get; set; }
        public int CmntDislike { get; set; }
        public System.Guid CommentUniqueCode { get; set; }
    }
}
